apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: ${IMAGE_NAME}:${IMAGE_VERSION}
          ports:
            - containerPort: ${SERVICE_PORT}

---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}-service
  labels:
    app: ${SERVICE_NAME}
spec:
  selector:
    app: ${SERVICE_NAME}
  ports:
    - port: ${SERVICE_PORT}
      targetPort: ${SERVICE_PORT}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${SERVICE_NAME}-ingress
  labels:
    app: ${SERVICE_NAME}
spec:
  rules:
    - http:
        paths:
          - path: /front
            pathType: Prefix
            backend:
              service:
                name: ${SERVICE_NAME}-service
                port:
                  number: ${SERVICE_PORT}
